name: CI Build Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - develop/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm build
